#!/bin/bash

# Name of symolic link to this script should be ufenv-<app_name>-devtest-<app_target>.sh
CMD=$(basename -s ".sh" $_)
TMP1=(${CMD//-/ })
APP_CMD=${TMP1[0]}
APP_NAME=${TMP1[1]}
APP_CONF=${TMP1[2]}
APP_TARGET=${TMP1[3]}
EMPTY=${TMP1[4]}

if [[ "$APP_CMD" != "ufenv" ]] || [ -z "$APP_NAME" ] || [[ "$APP_CONF" != "devtest" ]] || [ -z "$APP_TARGET" ] || [ ! -z "$EMPTY"]; then
        echo "Script: $CMD"
	quit $'Invalid name of symbolic link to script, should be "ufenv-<app_name>-devtest-<app_target>.sh"'
fi

{% set hosts = pillar['ufconfig']['hosts'] -%}
# ufoffice-test1 containers generated by salt
declare -a test1containers=(
{%- for name in hosts|sort %}
{%- set host = hosts[name] %}
{%- if 'hidden' not in host or not host['hidden'] == True %}
{%- if 'absent' not in host or not  host['absent'] == True %}
{%- set hostname = host['networking']['hostname'] %}
{%- if 'ufoffice-test1' in hostname %}
{%- if host['container'] is defined %}
 "{{hostname}}"
{%- endif %}
{%- endif %}
{%- endif %}
{%- endif %}
{%- endfor %}
)

# ufoffice-test3 containers generated by salt
declare -a test3containers=(
{%- for name in hosts|sort %}
{%- set host = hosts[name] %}
{%- if 'hidden' not in host or not host['hidden'] == True %}
{%- if 'absent' not in host or not  host['absent'] == True %}
{%- set hostname = host['networking']['hostname'] %}
{%- if 'ufoffice-test3' in hostname %}
{%- if host['container'] is defined %}
 "{{hostname}}"
{%- endif %}
{%- endif %}
{%- endif %}
{%- endif %}
{%- endfor %}
)

if [[ " ${test3containers[*]} " =~ " ufoffice-test3-${APP_TARGET} " ]]; then
    declare -A TARGET_WAR_APP_MAP
    TARGET_WAR_APP_MAP["ufoffice-salt1"]="ufoffice-test3-${APP_TARGET}"
    TARGET_WEB="ufoffice-test3-${APP_TARGET}"
fi

if [[ " ${test1containers[*]} " =~ " ufoffice-test1-${APP_TARGET} " ]]; then
    declare -A TARGET_WAR_APP_MAP
    TARGET_WAR_APP_MAP["ufoffice-salt1"]="ufoffice-test1-${APP_TARGET}"
    TARGET_WEB="ufoffice-test1-${APP_TARGET}"
fi

TARGET_APP_PORT=8284
TARGET_APP="${TARGET_WAR_APP_MAP[@]}"

TARGET_WAR_PORT=8283
TARGET_WAR="${!TARGET_WAR_APP_MAP[@]}"

TARGET_WEB_PORT=8283

#TARGET_DNS_PORT=8284
#TARGET_DNS="aws1-dns1"

LINKS="https://uo-${APP_TARGET}.test.unifaun.com/"
