#!/bin/bash

declare -A TARGET_WAR_APP_MAP
TARGET_WAR_APP_MAP["ufcolo1-app1"]="ufcolo1-app1-ee ufcolo1-app2-ee"
TARGET_WAR_APP_MAP["ufcolo2-app1"]="ufcolo2-app1-ee ufcolo2-app2-ee"

TARGET_APP_PORT=8283
TARGET_APP="${TARGET_WAR_APP_MAP[@]}"

TARGET_WAR_PORT=8283
TARGET_WAR="${!TARGET_WAR_APP_MAP[@]}"

TARGET_WEB_PORT=
TARGET_WEB=

TARGET_DNS_PORT=
TARGET_DNS=
