#!/bin/bash

TARGET_APP_PORT=8283
TARGET_APP_WEB_PORT=8183
TARGET_APP_SHUTDOWN_PORT=8171
TARGET_APP="ufoffice-test2"

declare -A TARGET_SITE_DB_SERVER_MAP
TARGET_SITE_DB_SERVER_MAP["ufcolo1"]="ufoffice-test2-ee1"
TARGET_SITE_DB_SERVER_MAP["ufcolo2"]="ufoffice-test2-ee2"

TARGET_DB_SERVER="${TARGET_SITE_DB_SERVER_MAP[@]}"
TARGET_SITE="${!TARGET_SITE_DB_SERVER_MAP[@]}"

TARGET_DB_CLUSTER_NAME=main
TARGET_DB_CLUSTER_VERSION=9.4

TARGET_DB_PRI_GROUPS=""
TARGET_DB_SEC_GROUPS=""

TARGET_DB_PORT=8283
TARGET_LOCAL_PORT=8183

# If a master database is down, add its replica to the TARGET_DB_SERVER_FORCE_PROMOTE list, this promote it without first require that it is up to date with the old master 
TARGET_DB_SERVER_FORCE_PROMOTE=""