driver:
  name: docker
  use_sudo: false
  privileged: true
  ssh_timeout: 5
  ssh_retries: 5
  public_key: .kitchen/docker_id_rsa.pub
  private_key: .kitchen/docker_id_rsa
  forward:
    - 80

transport:
  name: docker
  # log_level: :debug

provisioner:
  name: salt_solo
  #log_level: debug
  salt_install: none
  require_chef: false
  is_file_root: true
  salt_copy_filter:
    - .git
    - .kitchen
    - Gemfile
    - Gemfile.lock
    - pytests_cache
    - docker-scripts
    - script.sh
    - requirements.txt
    - LICENSE
    - .kitchen.yml
    - README.md

platforms:
  - name: ubuntu-22.04
    driver_config:
      image: ubuntu2204_salt_minion
      platform: ubuntu
      hostname: ubuntu2204.local
      container_name: u2204
      instance_name: u2204
  # - name: ubuntu-20.04
  #   driver_config:
  #     image: ubuntu2004_salt_minion
  #     platform: ubuntu
  #     hostname: ubuntu2004.local
  #     container_name: u2004
  #     instance_name: u2004
  # - name: ubuntu-18.04
  #   driver_config:
  #     image: ubuntu1804_salt_minion
  #     platform: ubuntu
  #     hostname: ubuntu1804.local
  #     container_name: u1804
  #     instance_name: u1804
  # - name: ubuntu-14.04
  #   driver_config:
  #     image: ubuntu1404_salt_minion
  #     platform: ubuntu
  #     hostname: ubuntu1404.local
  #     container_name: u1404
  #     instance_name: u1404

suites:
  - name: sample
    provisioner:
      state_top:
        base:
          '*':
            - aformula
            - bformula
      pillars:
        top.sls:
          base:
            '*':
              - aformula
              - bformula
      pillars_from_directories:
      - pillars
    verifier:
      name: shell
      remote_exec: false
      command: python3 -m pytest -v tests/  


